import type { WeeklyInsight } from "../types";

interface Props {
  data: WeeklyInsight;
}

export function WeeklyInsightCard({ data }: Props) {
  return (
    <div className="insight">
      <ul>
        {data.bullets.map((b, i) => (
          <li key={i}>{b}</li>
        ))}
      </ul>
      <div className="source">
        {data.week_start} → {data.week_end} ·{" "}
        {data.source === "claude" ? "Generated by Claude" : "Heuristic summary (set ANTHROPIC_API_KEY for AI)"}
      </div>
    </div>
  );
}
